### ISSUE TITLE
Multi-line notifications on windows 10 show \n instead of a line break

### ISSUE THREAD

**Issue by aplex** [mikaelbr/node-notifier#123]
Multi-line notifications on windows 10 show "\n" instead of a line break.

Show notification with message `line1\nline2`

Expected result:

```
line1
line2
```

Actual result:
`line1\nline2`

v4.6.0

Previous version 4.5 showed multi-line notifications on some windows 10 computers, and showed "\n" on others.

**Comment by Knagis** [comment]
I had the exact same issue right now 

* node-notifier 4.6.0
* Windows 10 build 10586.456
* node version 6.0.0

**Comment by Titozzz** [comment]
Same issue here

**Comment by mikaelbr** [comment]
Is this also an issue using this branch? https://github.com/mikaelbr/node-notifier/pull/134

**Comment by ew72ew** [comment]
The problem is here:
https://github.com/mikaelbr/node-notifier/blob/master/lib/utils.js#L263

Avoiding this string replace will enable line breaks on Windows 10 with toast.exe.

**Comment by mikaelbr** [comment]
This should hopefully be fixed in the latest version in the master branch. Would love it if you could test it out:

```
npm i mikaelbr/node-notifier
```

**Comment by ew72ew** [comment]
It seems to use SnoreToast.exe instead of toast.exe and basically it works now :thumbsup:

Unfortunately I am using this through gulp-notify and when it is about to toast an error this happens:

> gulp-notify: [Error running notifier] Could not send message: Command failed: xyz\node_modules\node-notifier\vendor\snoreToast\SnoreToast.exe **-open  -subtitle** -p xyz\node_modules\gulp-notify\assets\gulp-error.png -m message1\r\nmessage2 -t title

In that case it will also send "open" and "subtitle" options which SnoreToast cannot process and fails.

I tried a quick hack in toaster.js which fixed it:
```javascript
delete options.open;
delete options.subtitle;
```

Hope it helps.

**Comment by mikaelbr** [comment]
Thanks! It seems SnoreToast doesn't allow surplus arguments, so need to filter out things and not let notifier be transient with options as with notification center on Mac. Thanks for the code & comments! I've got access to windows versions at work now, so I can test and fix it within the day.

**Comment by mikaelbr** [comment]
@ew72ew How is the master branch now? I've added several tests, implemented better support for all-things snoretoasts.

**Comment by ew72ew** [comment]
The linebreaks work now. Definitely!

Now there is only the problem with the default sound left. Since it is gulp-notify related, I am not sure if it should be fixed here or there.

gulp-notify sets this defaults:
```javascript
var defaults = {
  error: {
    icon: path.join(__dirname, '..', 'assets', 'gulp-error.png'),
    sound: 'Frog'
  },
  regular: {
    icon: path.join(__dirname, '..', 'assets', 'gulp.png')
  }
};
```

## Error message
So if an error happens it will execute the following command:
```
xyz\SnoreToast.exe -p xyz\gulp-error.png -m Error message -t Title -s Frog
```

However SnoreToast.exe fails if "Frog" is supplied as the sound. It still displays the toast, plays the default Windows sound but it ignores the custom image, always has the title "SnoreToast" and no message.

To make it work, one of these must be used instead:
```bash
# If no sound is supplied, it will always use the default Windows sound
xyz\SnoreToast.exe -p xyz\gulp-error.png -m Error message -t Title

# Alternatively a valid sound must be used
xyz\SnoreToast.exe -p xyz\gulp-error.png -m Error message -t Title -s Notification.Default
```

A quick hack could be:
```javascript
  if (options.sound) {
    options.s = options.sound;
    delete options.sound;

    // "Frog" is set by gulp-notify for errors but is not a valid Windows sound
    if (options.s === 'Frog') {
      options.s = 'Notification.Default';
    }
  }
```

## Success message

The success message on the other hand uses the following command:
```
xyz\SnoreToast.exe -p xyz\gulp.png -m Success message -t Title
```

And this also generates the default Windows sound. It should be really using this command:
```
xyz\SnoreToast.exe -p xyz\gulp.png -m Success message -t Title -silent
```

This is how toast.exe worked. Success messages were silent, so we need the `-silent` option to prevent the default sound.

## Possible solution

1. Silent should be true by default
2. If a sound is provided, silent should be removed
3. Either the "Frog" exception has to be added or another validation to make sure the sound is valid

Hope it helps and thank you for working on it!

**Comment by mikaelbr** [comment]
Thanks for the detailed feedback. The problem is managing sound in a cross platform manner, where if you use `Frog` on Mac you shouldn't crash on windows. I think maybe one way to solve this is to validate input sound and if it doesn't match use a default sound. I think this is OK as when you choose a sound, it's expected to get a sound, not silent.

**Comment by mikaelbr** [comment]
It should work better now with sound. Still not cross platform in the sense that it is the same sound, but at least it won't crash.

**Comment by mikaelbr** [comment]
Closing this as fix is verified. Will be released in v5 soon.
