### ISSUE TITLE
It doesn't work on MacOS BigSur

### ISSUE THREAD

**Issue by MaxLevs** [mikaelbr/node-notifier#364]
I was trying to run examples:mac:input it on MacOS BigSur. And nothing happened. It just waited some time and closed with timeout event.

**Comment by vikasraj789** [comment]
@MaxLevs Can you share how it was resolved, as I am facing the same issue in MacOS BigSur.

**Comment by MaxLevs** [comment]
@vikasraj789 I didn't resolve it. I've just use another way.

**Comment by vikasraj789** [comment]
@MaxLevs Thanks for you prompt reply. Can you let me know the alternative you have used?

**Comment by MaxLevs** [comment]
> @MaxLevs Thanks for your prompt reply. Can you let me know the alternative you have used?

I run terminal command via node.js. There is [terminal-notifier](https://github.com/julienXX/terminal-notifier) that can make notifications through terminal. It looks like a trash but still works.

**Comment by vikasraj789** [comment]
@MaxLevs Thanks

**Comment by LucaAlicata** [comment]
check if you have "do not disturb" on, that was my problem
